{
    "extends": ["eslint:recommended"],
    "parserOptions": {
        "ecmaVersion": 2017
    },
    "env": { "es6": true, "node": true, "mocha": true },
    "rules": {
        "semi": [ 1, "never" ],
        "no-console": 0
    },
    "plugins": [ "mocha" ]
}
