service: parcelize-csv

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Resource: "*"
      Action:
        - ses:SendEmail
        - ses:SendRawEmail

functions:
  listen: 
    handler: src/app.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
    environment:
      ENV: aws
    iamRoleStatements:
      - Effect: Allow
        Resource: "*"
        Action:
          - ses:SendEmail
          - ses:SendRawEmail
package:
  include:
    - src/**
