service: parcelize

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Resource: "*"
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
        - s3:*

functions:
  authorize:
    handler: src/authorize.handler
    environment:
      JWT_SECRET: "f98dhiu3hgfsudy342tuisedogwuy3i87Aa"
  
  createUser:
    handler: src/createUser.handler
    events:
        - http:
            path: /create-user
            method: post
            cors: true
    environment:
      PARCELIZE_MLAB_CONNECT: ${env:PARCELIZE_MLAB_CONNECT}
      SLS_DEBUG: "*"
      JWT_SECRET: "f98dhiu3hgfsudy342tuisedogwuy3i87Aa"

  verifyUser:
    handler: src/verifyUser.handler
    events:
        - http:
            path: /verify-user
            method: get
            authorizer: authorize
            cors: true
    environment:
      PARCELIZE_MLAB_CONNECT: ${env:PARCELIZE_MLAB_CONNECT}
      SLS_DEBUG: "*"
      JWT_SECRET: "f98dhiu3hgfsudy342tuisedogwuy3i87Aa"
  
  authenticateUser:
    handler: src/authenticateUser.handler
    events:
        - http:
            path: /authenticate-user
            method: post
            authorizer: authorize
            cors: true
    environment:
      PARCELIZE_MLAB_CONNECT: ${env:PARCELIZE_MLAB_CONNECT}
      SLS_DEBUG: "*"
      JWT_SECRET: "f98dhiu3hgfsudy342tuisedogwuy3i87Aa"

  login:
    handler: src/login.handler
    events:
        - http:
            path: /login
            method: post
            cors: true
    environment:
      PARCELIZE_MLAB_CONNECT: ${env:PARCELIZE_MLAB_CONNECT}
      SLS_DEBUG: "*"
      JWT_SECRET: "f98dhiu3hgfsudy342tuisedogwuy3i87Aa"

  train:
    handler: src/train.handler
    events:
      - http:
          path: /train
          method: post
          authorizer: authorize
          cors: true
    environment:
      PARCELIZE_MLAB_CONNECT: ${env:PARCELIZE_MLAB_CONNECT}
      SLS_DEBUG: "*"
  
  trainingData:
    handler: src/trainingData.handler
    events:
      - http:
          path: /training-data
          method: get
          authorizer: authorize
          cors: true
    environment:
      PARCELIZE_MLAB_CONNECT: ${env:PARCELIZE_MLAB_CONNECT}
      SLS_DEBUG: "*"
      JWT_SECRET: "f98dhiu3hgfsudy342tuisedogwuy3i87Aa"

  classify:
     handler: src/classify.handler
     events:
       - http:
          path: /classify
          method: post
          authorizer: authorize
          cors: true
     environment:
       PARCELIZE_MLAB_CONNECT: ${env:PARCELIZE_MLAB_CONNECT}
       SLS_DEBUG: "*"
       JWT_SECRET: "f98dhiu3hgfsudy342tuisedogwuy3i87Aa"
  
  downloadBucket:
     handler: src/downloadBucket.handler
     events:
       - http:
          path: /download-bucket
          method: post
          authorizer: authorize
          cors: true
     environment:
       PARCELIZE_MLAB_CONNECT: ${env:PARCELIZE_MLAB_CONNECT}
       SLS_DEBUG: "*"
       JWT_SECRET: "f98dhiu3hgfsudy342tuisedogwuy3i87Aa"


package:
  include:
    - src/**

plugins:
  - serverless-offline

custom:
    serverless-offline:
        port: 4000
